version: '3.7'

services:
  agile:
    image: agile:latest
    container_name: agile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agile.rule=Host(`agile.yoda.vm`)"
      - "traefik.http.routers.agile.entrypoints=web"
      - "traefik.http.services.agile.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - postgresql_pg_network

volumes:
  registry-data:

networks:
  postgresql_pg_network:
    external: true
  traefik_proxy:
    external: true

