version: '3.7'

services:
  agile:
    image: agile:latest
    container_name: agile
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agile.rule=Host(`agile.yoda.vm`)"
      - "traefik.http.routers.agile.entrypoints=web"
      - "traefik.http.services.agile.loadbalancer.server.port=80"
    networks:
      - traefik_proxy

volumes:
  registry-data:

networks:
  traefik_proxy:
    external: true

